spring:
  application:
    name: vehicle-maintenance-scheduler
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:h2:mem:vehicledb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8081
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO
    com.logistics: DEBUG

external:
  api:
    depot-url: http://4.224.186.213/evaluation-service/depots
    api-key: YOUR_API_KEY_HERE
    connection-timeout: 10000
    read-timeout: 10000
